### ISSUE TITLE
下载下来的工程问题

### ISSUE THREAD

**Issue by shuaiwang007** [HansRove/iOSBridgeFlutterDemo#2]
![屏幕快照 2019-03-26 下午3 36 16](https://user-images.githubusercontent.com/12870683/54979032-044c8080-4fdd-11e9-846a-9a64ae2885c4.png)
下载下来的flutter_module文件里没有 隐藏的 .ios 和 .andriod文件

**Comment by HansRove** [comment]
> ![屏幕快照 2019-03-26 下午3 36 16](https://user-images.githubusercontent.com/12870683/54979032-044c8080-4fdd-11e9-846a-9a64ae2885c4.png)
> 下载下来的flutter_module文件里没有 隐藏的 .ios 和 .andriod文件

命令行flutter_module目录下执行: ` flutter create -t module . `     看一下会不会出来!
